server.port=8081

eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=*

# Database
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/your_database
spring.datasource.username=root
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
