apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1

  selector:
    matchLabels:
      app: notification-service

  template:
    metadata:
      labels:
        app: notification-service

    spec:
      containers:
        - name: notification-service
          image: notification-service:1.3
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8084

          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8888"

            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"