apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1

  selector:
    matchLabels:
      app: order-service

  template:
    metadata:
      labels:
        app: order-service

    spec:
      containers:
        - name: order-service
          image: order-service:2.4
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8083

          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8888"

            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"