spring.application.name=order-service
server.port=8083

logging.level.com.ravindra=DEBUG
logging.level.org.springframework.web=DEBUG

jwt.secret=MySecretKeyForJwtAuthentication12345678901234567890
jwt.expiration=3600000

