spring.application.name=config-server
server.port=8888

spring.cloud.config.server.git.uri=https://github.com/nagoderavindra/Ecommerce-project.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true

# Eureka - Docker
eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true